/**
 * Canonical 19 MBBS subject list with starter topics.
 * Used by:
 *   - prisma/seed.ts (CLI: `npm run db:seed`)
 *   - src/lib/seed-once.ts (auto-seed on first request)
 */
export type TopicSeed = { slug: string; name: string };
export type SubjectSeed = {
  slug: string;
  name: string;
  shortName?: string;
  description: string;
  color: string;
  icon: string;
  order: number;
  topics: TopicSeed[];
};

export const SUBJECTS: SubjectSeed[] = [
  {
    slug: "anatomy",
    name: "Anatomy",
    shortName: "Anat",
    description: "Gross anatomy, histology, embryology and neuroanatomy of the human body.",
    color: "#4F8CFF",
    icon: "Bone",
    order: 1,
    topics: [
      { slug: "upper-limb", name: "Upper Limb" },
      { slug: "lower-limb", name: "Lower Limb" },
      { slug: "thorax", name: "Thorax" },
      { slug: "abdomen-pelvis", name: "Abdomen & Pelvis" },
      { slug: "head-neck", name: "Head & Neck" },
      { slug: "neuroanatomy", name: "Neuroanatomy" },
      { slug: "embryology", name: "Embryology" },
      { slug: "histology", name: "Histology" },
    ],
  },
  {
    slug: "physiology",
    name: "Physiology",
    shortName: "Physio",
    description: "Normal functions of the human body at cellular, organ and system levels.",
    color: "#00E5A8",
    icon: "HeartPulse",
    order: 2,
    topics: [
      { slug: "general-physiology", name: "General Physiology" },
      { slug: "nerve-muscle", name: "Nerve & Muscle" },
      { slug: "blood", name: "Blood" },
      { slug: "cardiovascular", name: "Cardiovascular System" },
      { slug: "respiratory", name: "Respiratory System" },
      { slug: "renal", name: "Renal System" },
      { slug: "gi-physiology", name: "GI System" },
      { slug: "endocrine", name: "Endocrine" },
      { slug: "reproductive", name: "Reproductive" },
      { slug: "neurophysiology", name: "Neurophysiology" },
    ],
  },
  {
    slug: "biochemistry",
    name: "Biochemistry",
    shortName: "Biochem",
    description: "Chemistry of life: enzymes, metabolism, molecular biology and nutrition.",
    color: "#F59E0B",
    icon: "FlaskConical",
    order: 3,
    topics: [
      { slug: "enzymes", name: "Enzymes" },
      { slug: "carbohydrates", name: "Carbohydrate Metabolism" },
      { slug: "lipids", name: "Lipid Metabolism" },
      { slug: "proteins-aa", name: "Proteins & Amino Acids" },
      { slug: "nucleic-acids", name: "Nucleic Acid Metabolism" },
      { slug: "vitamins", name: "Vitamins" },
      { slug: "minerals", name: "Minerals" },
      { slug: "molecular-biology", name: "Molecular Biology" },
    ],
  },
  {
    slug: "pathology",
    name: "Pathology",
    shortName: "Path",
    description: "Mechanisms of disease: cellular injury, inflammation, neoplasia and systems.",
    color: "#EF4444",
    icon: "Microscope",
    order: 4,
    topics: [
      { slug: "general-pathology", name: "General Pathology" },
      { slug: "hematology", name: "Hematology" },
      { slug: "systemic-path", name: "Systemic Pathology" },
      { slug: "cardio-path", name: "Cardiovascular Pathology" },
      { slug: "respiratory-path", name: "Respiratory Pathology" },
      { slug: "gi-path", name: "GI & Hepatobiliary Pathology" },
      { slug: "renal-path", name: "Renal Pathology" },
      { slug: "neuro-path", name: "Neuropathology" },
      { slug: "endocrine-path", name: "Endocrine Pathology" },
    ],
  },
  {
    slug: "microbiology",
    name: "Microbiology",
    shortName: "Micro",
    description: "Bacteriology, virology, mycology, parasitology and immunology.",
    color: "#A78BFA",
    icon: "Bug",
    order: 5,
    topics: [
      { slug: "general-micro", name: "General Microbiology" },
      { slug: "bacteriology", name: "Bacteriology" },
      { slug: "virology", name: "Virology" },
      { slug: "mycology", name: "Mycology" },
      { slug: "parasitology", name: "Parasitology" },
      { slug: "immunology", name: "Immunology" },
      { slug: "applied-micro", name: "Applied Microbiology" },
    ],
  },
  {
    slug: "pharmacology",
    name: "Pharmacology",
    shortName: "Pharma",
    description: "Drug actions, pharmacokinetics, therapeutics and toxicology.",
    color: "#22C55E",
    icon: "Pill",
    order: 6,
    topics: [
      { slug: "general-pharma", name: "General Pharmacology" },
      { slug: "ans-pharma", name: "Autonomic Nervous System" },
      { slug: "cns-pharma", name: "CNS Pharmacology" },
      { slug: "cardio-pharma", name: "Cardiovascular Pharmacology" },
      { slug: "endocrine-pharma", name: "Endocrine Pharmacology" },
      { slug: "chemotherapy", name: "Chemotherapy" },
      { slug: "autacoids", name: "Autacoids" },
      { slug: "git-pharma", name: "GI Pharmacology" },
    ],
  },
  {
    slug: "forensic-medicine",
    name: "Forensic Medicine & Toxicology (FMT)",
    shortName: "FMT",
    description: "Legal aspects of medicine, identification, trauma and toxicology.",
    color: "#64748B",
    icon: "Scale",
    order: 7,
    topics: [
      { slug: "forensic-basics", name: "Forensic Basics" },
      { slug: "identification", name: "Identification" },
      { slug: "trauma", name: "Trauma & Wounds" },
      { slug: "toxicology", name: "Toxicology" },
      { slug: "sexual-offences", name: "Sexual Offences" },
    ],
  },
  {
    slug: "community-medicine",
    name: "Community Medicine (PSM/SPM)",
    shortName: "PSM",
    description: "Preventive and social medicine, epidemiology, biostatistics and public health.",
    color: "#06B6D4",
    icon: "Globe",
    order: 8,
    topics: [
      { slug: "epidemiology", name: "Epidemiology" },
      { slug: "biostatistics", name: "Biostatistics" },
      { slug: "nutrition", name: "Nutrition" },
      { slug: "communicable-diseases", name: "Communicable Diseases" },
      { slug: "non-communicable", name: "Non-communicable Diseases" },
      { slug: "mch", name: "Maternal & Child Health" },
      { slug: "health-programs", name: "National Health Programmes" },
    ],
  },
  {
    slug: "general-medicine",
    name: "General Medicine",
    shortName: "Medicine",
    description: "Diagnosis and management of adult medical illnesses.",
    color: "#FB7185",
    icon: "Stethoscope",
    order: 9,
    topics: [
      { slug: "cardiology", name: "Cardiology" },
      { slug: "pulmonology", name: "Pulmonology" },
      { slug: "gastroenterology", name: "Gastroenterology" },
      { slug: "nephrology", name: "Nephrology" },
      { slug: "endocrinology", name: "Endocrinology" },
      { slug: "hematology-medicine", name: "Hematology" },
      { slug: "neurology", name: "Neurology" },
      { slug: "infectious-diseases", name: "Infectious Diseases" },
      { slug: "rheumatology", name: "Rheumatology" },
    ],
  },
  {
    slug: "general-surgery",
    name: "General Surgery",
    shortName: "Surgery",
    description: "Principles of surgery and common surgical conditions.",
    color: "#34D399",
    icon: "Scissors",
    order: 10,
    topics: [
      { slug: "general-sx", name: "General Surgery" },
      { slug: "gi-sx", name: "GI Surgery" },
      { slug: "trauma-sx", name: "Trauma Surgery" },
      { slug: "vascular-sx", name: "Vascular Surgery" },
      { slug: "urology", name: "Urology" },
      { slug: "oncology-sx", name: "Surgical Oncology" },
    ],
  },
  {
    slug: "obg",
    name: "Obstetrics & Gynaecology (OBG)",
    shortName: "OBG",
    description: "Pregnancy, childbirth, reproductive health and women's diseases.",
    color: "#F472B6",
    icon: "Baby",
    order: 11,
    topics: [
      { slug: "obstetrics", name: "Obstetrics" },
      { slug: "gynecology", name: "Gynecology" },
      { slug: "reproductive-endocrine", name: "Reproductive Endocrinology" },
      { slug: "obg-oncology", name: "Gynecological Oncology" },
    ],
  },
  {
    slug: "pediatrics",
    name: "Pediatrics",
    shortName: "Peds",
    description: "Child health from neonates to adolescents.",
    color: "#A3E635",
    icon: "Smile",
    order: 12,
    topics: [
      { slug: "neonatology", name: "Neonatology" },
      { slug: "growth-development", name: "Growth & Development" },
      { slug: "pediatric-infections", name: "Pediatric Infections" },
      { slug: "pediatric-nutrition", name: "Pediatric Nutrition" },
      { slug: "pediatric-systems", name: "Systemic Pediatrics" },
    ],
  },
  {
    slug: "ophthalmology",
    name: "Ophthalmology",
    shortName: "Ophth",
    description: "Eye diseases, vision and ocular surgery.",
    color: "#60A5FA",
    icon: "Eye",
    order: 13,
    topics: [
      { slug: "anatomy-eye", name: "Anatomy of Eye" },
      { slug: "refraction", name: "Refraction & Optics" },
      { slug: "retina", name: "Retina & Vitreous" },
      { slug: "glaucoma", name: "Glaucoma" },
      { slug: "cornea", name: "Cornea & Conjunctiva" },
    ],
  },
  {
    slug: "ent",
    name: "Otorhinolaryngology (ENT)",
    shortName: "ENT",
    description: "Ear, nose and throat diseases and surgery.",
    color: "#FBBF24",
    icon: "Ear",
    order: 14,
    topics: [
      { slug: "ear", name: "Ear" },
      { slug: "nose", name: "Nose & Paranasal Sinuses" },
      { slug: "throat", name: "Throat & Larynx" },
      { slug: "head-neck-ent", name: "Head & Neck" },
    ],
  },
  {
    slug: "orthopedics",
    name: "Orthopaedics",
    shortName: "Ortho",
    description: "Musculoskeletal injuries and disorders.",
    color: "#C084FC",
    icon: "Bone",
    order: 15,
    topics: [
      { slug: "fractures", name: "Fractures & Trauma" },
      { slug: "joint-disorders", name: "Joint Disorders" },
      { slug: "spine", name: "Spine" },
      { slug: "pediatric-ortho", name: "Pediatric Orthopedics" },
    ],
  },
  {
    slug: "dermatology",
    name: "Dermatology, Venereology & Leprosy (DVL)",
    shortName: "DVL",
    description: "Skin, hair, nail disorders and STDs.",
    color: "#F87171",
    icon: "Sparkles",
    order: 16,
    topics: [
      { slug: "general-derm", name: "General Dermatology" },
      { slug: "infections-skin", name: "Skin Infections" },
      { slug: "std", name: "Sexually Transmitted Diseases" },
      { slug: "systemic-derm", name: "Systemic Dermatology" },
    ],
  },
  {
    slug: "psychiatry",
    name: "Psychiatry",
    shortName: "Psych",
    description: "Mental, behavioral and substance-use disorders.",
    color: "#818CF8",
    icon: "Brain",
    order: 17,
    topics: [
      { slug: "general-psych", name: "General Psychiatry" },
      { slug: "schizophrenia", name: "Schizophrenia & Psychosis" },
      { slug: "mood-disorders", name: "Mood Disorders" },
      { slug: "anxiety", name: "Anxiety Disorders" },
      { slug: "child-psych", name: "Child & Adolescent Psychiatry" },
    ],
  },
  {
    slug: "anesthesiology",
    name: "Anaesthesiology",
    shortName: "Anaesth",
    description: "Anesthesia, pain management and critical care.",
    color: "#4ADE80",
    icon: "Syringe",
    order: 18,
    topics: [
      { slug: "general-anesth", name: "General Anesthesia" },
      { slug: "regional-anesth", name: "Regional Anesthesia" },
      { slug: "pain-management", name: "Pain Management" },
      { slug: "critical-care", name: "Critical Care" },
    ],
  },
  {
    slug: "radiology",
    name: "Radiodiagnosis (Radiology)",
    shortName: "Radio",
    description: "Imaging modalities: X-ray, CT, MRI, ultrasound and interventional.",
    color: "#38BDF8",
    icon: "Scan",
    order: 19,
    topics: [
      { slug: "general-radio", name: "General Radiology" },
      { slug: "xray-basics", name: "X-ray Basics" },
      { slug: "ct-mri", name: "CT & MRI" },
      { slug: "interventional-radio", name: "Interventional Radiology" },
    ],
  },
];
